### PR TITLE
Remove Bclose dependency

### LINKED ISSUE #14: Wrong buffer displayed when lf is closed
I just noticed a strange bug after using lf for some time. Here is how to reproduce it:

Open nvim with several files as arguments:
```zsh
nvim a.txt b.txt c.txt
```
The file `a.txt` will be displayed on start. Open and quit the lf plugin. File `c.txt` gets displayed. I think that the correct behavior is to display the buffer from which you launched lf.

### PR DESCRIPTION
**Pull request by mroavi**
Fixes #14
Updated README

### CODE REVIEW

**Comment by ptzz** [comment]
I noticed that vim-bbye plugin solves #14 and pushed a fix. In general it looks like a polished version of bclose.vim.

Getting rid of the dependency altogether would be better still. However I don't have the time to test the apparently numerous buffer close corner cases that the plugin handles.

**Comment by mroavi** [comment]
I see. By the way, If you would like to pass on the maintenance of this package given that you are not using it anymore, let me know.

**Comment by ptzz** [comment]
Awesome, I’ve sent you a collaborator invitation!

**Comment by mroavi** [comment]
@ptzz I'm actually going to have to step back. I found an alternative that supports floating windows. Sorry for the false alarm.

**Comment by ptzz** [comment]
No worries, which is the alternative?

**Comment by mroavi** [comment]
I'm gonna take advantage of open-source software. I know that the [nnn](https://github.com/mcchrish/nnn.vim) plugin supports this feature and I noticed that I can make it work for lf just by changing one line. So I ended up forking the plugin and adapting it for lf.

**Comment by ptzz** [comment]
FYI floating window support was just merged: https://github.com/ptzz/lf.vim/pull/10.

**Pull request closed without merging**
